### ISSUE TITLE
LP timer is running ~1.25x too fast

### ISSUE THREAD

**Issue by niklas-arm** [ARMmbed/mbed-hal-st-stm32f4#20]
The LP timer is running about 1.25 times too fast on the STM32F429I Discovery running at 168MHz.

There is also a bug that a frequency is divided by a 1GHz value, which is of course nonsense:
https://github.com/ARMmbed/mbed-hal-st-stm32f4/blob/master/source/lp_ticker.c#L48

**Comment by betzw** [comment]
A fix for this can be found in https://github.com/betzw/mbed-hal-st-stm32f4/tree/betzw_wb

**Comment by 0xc0170** [comment]
@betzw Are you planning to send a fix ?

**Comment by betzw** [comment]
We are currently working together with @screamerbg on a port to Nucleo-STM32F401RE and have a first version pushed to github. I do niot know how @screamerbg (Mihail Stoyanov) is planning to proceed on this?

**Comment by 0xc0170** [comment]
lp ticker should be implemented on top of RTC, and this high-precision timer released for other use. 

@betzw  Are there any plans for this?

**Comment by betzw** [comment]
In the mid-term, the answer is that using a RTC is clearly the right choice.
But currently we are all focused on TechCon demos ...

**Comment by niklas-arm** [comment]
@betzw I don't understand your fix:
Doesn't Timer2 run from the APB1 clock domain, ie. which has a max. clock frequency limitation of 45MHz?
So the APB1 prescaler must be set to 4 (168MHz/4 = 42MHz < 45MHz), which means the Timer input clocks are multiplied by 2, ie. they run on 84MHz, aka. `SystemCoreClock / 2`?

Unfortunately the clock tree documentation in the F429 Reference Manual isn't very clear about which peripherals are powered by what clock domains.

**Comment by niklas-arm** [comment]
@betzw please see the fix for this for you port of the F401.

**Comment by simonqhughes** [comment]
ARM Internal Ref: IOTSFW-1065

**Comment by betzw** [comment]
Well not sure I understand your comments. In any case let me explain my implementation:
The prescaler register of a timer has only 16-bits. The dafult SystemCoreClock on a NUCLEO-STM32F401RE is 84Mhz, which means that the value you need to put in the prescaler in order to obtain a 1ms tick is beyond the highest value you can put in the prescaler register (as it would require more than 16 bits). At that point I decide to put the highest possible prescaler value into the prescaler register in order to obtain the slowest tick ferquency possible and adjust the MINAR_PLATFORM_TIME_BASE value accordignly: https://github.com/betzw/mbed-hal-st-stm32f401re/blob/betzw_wb/mbed-hal-st-stm32f401re/target_config.h#L21.
Hope this helps.
